### ISSUE TITLE
参考书中有一处疏忽。

### ISSUE THREAD

**Issue by j-xzy** [markjenny/my_ucore_os_lab#1]
https://chyyuu.gitbooks.io/ucore_os_docs/content/lab1/lab1_3_2_1_protection_mode.html 中在介绍段属性时，重复介绍了“粒度位”。

**Comment by markjenny** [comment]
通过你的叙述我也看到了，不过我现在的repo是自己的，和chyyuu这个用户没有关系，所以你可能需要再去chyyuu这个用户下面去体issue了，:)
